esphome:
  name: thermout

esp32:
  board: esp32-c3-devkitm-1
  framework:
    type: arduino

wifi:
  !secret wifi

# Enable logging
logger:
  level: INFO

mqtt:
  !secret mqtt

i2c:
  sda: GPIO5
  scl: GPIO4
  scan: true
  frequency: 400khz

deep_sleep:
  run_duration: 1s
  sleep_duration: 30min

sensor:
  - platform: sht3xd
    temperature:
      name: "Temperature"
      on_value:
        then:
          - mqtt.publish:
              topic: s1/temperature
              payload: "{}"
    humidity:
      name: "Humidity"
      on_value:
        then:
          - mqtt.publish:
              topic: s1/humidity
              payload: "{}"
  - platform: adc
    pin: GPIO0
    name: "Battery Voltage"
    unit_of_measurement: "V"
    filters:
      - multiply: 5.14
